name: codelab
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.5.3

dependencies: 
  get: 4.6.6
  flutter: 
    sdk: flutter


  google_fonts: ^6.2.1
  ionicons: ^0.2.2
  carousel_slider: ^5.0.0
  flutter_carousel_slider_plus: ^0.0.1
  flutter_snake_navigationbar: ^0.6.1
  awesome_bottom_bar: ^1.2.4
  floating_navbar: ^2.0.2
  # flutter_image_compress: ^2.3.0
  image_picker: ^1.0.8
  image_cropper : ^1.3.1
  dotted_border: ^2.0.0
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  http: ^1.2.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  
  assets:
  - assets/reno.jpg
  - assets/dummycover.jpg
  - assets/logo.png

